name: agentic_rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - sentence-transformers
    - pymilvus
    - openai
    - torch
    - fastapi
    - uvicorn
    - python-dotenv
